[package]
description = "Rust bindings for tinykeccak C library"
homepage = "http://ethcore.io"
license = "GPL-3.0"
name = "sha3"
version = "0.1.0"
authors = ["Ethcore <admin@ethcore.io>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"
