[package]
description = "Large fixed-size integers and hash function outputs"
homepage = "http://ethcore.io"
repository = "https://github.com/ethcore/parity"
license = "GPL-3.0"
name = "ethcore-bigint"
version = "0.1.2"
authors = ["Ethcore <admin@ethcore.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
rustc-serialize = "0.3"
heapsize = "0.3"
rand = "0.3.12"

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]
